app.title=Spring External Resources Test
database.driverClassName=org.sqlite.JDBC
database.file=C:\\work\\training\\java\\users.db
database.defaultFile=C:\\work\\training\\java\\userdb.db
database.url=jdbc:sqlite:${database.file}