spring.application.name=spring-boot-web-exploration

spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:C:\\work\\training\\java\\userdb.db

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


database.url=jdbc:sqlite:C:\\work\\training\\java\\users.db
database.defaultFile=C:\\work\\training\\java\\users.db